module.exports = {
  SUCCESS: "success",
  BAD_REQUEST: "bad request",
  NOT_FOUND: "not found :{entity}",
  WRONG_PASSWORD: "wrong password",
  UNAUTHORIZED: "unauthorized",
  FORBIDDEN: "forbidden",
  MISSING_DATA: "missing information",
  INCORRECT_INFO: "username or password is incorrect",
  EXISTS_EMAIL: "email already exists",
  EXISTS_USERNAME: "username already exists",
  FILE_MISSING: "file missing",
  FILE_NOT_SUPPORT: "file type :{type} is not supported",
  INVALID_PASSWORD: "invalid password",
  INVALID_MAIL: "invalid email",
  INVALID_TOKEN: "invalid token",
  CHECK_EMAIL: "check your email",
  NOT_MEMBER: "user is not a member",
  INVALID_ROLE: "invalid role"
};
